apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-test
  namespace: chaos-mesh
spec:
  action: pod-failure
  mode: one
  duration: '30s'
  scheduler:
    cron: '@every 2m'
  selector:
    namespaces:
      - monitoring
    labelSelectors:
      'app.kubernetes.io/name': 'promtail'
