apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: broadcaster-dev
type: Opaque
stringData:
  POSTGRES_DB: broadcaster
  POSTGRES_USER: broadcaster_admin
  POSTGRES_PASSWORD: BroadCasterSecurePass2026!
