apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/woletokun/sre-gitops.git'
    targetRevision: test/trivy-pipeline
    path: apps/platform-system/kyverno
    helm:
      values: |
        kyverno:
          cleanupJobs:
            admissionReports:
              image:
                repository: registry.k8s.io/kubectl
                tag: v1.28.5
            clusterAdmissionReports:
              image:
                repository: registry.k8s.io/kubectl
                tag: v1.28.5
            clusterEphemeralReports:
              image:
                repository: registry.k8s.io/kubectl
                tag: v1.28.5
            ephemeralReports:
              image:
                repository: registry.k8s.io/kubectl
                tag: v1.28.5
            updateRequests:
              image:
                repository: registry.k8s.io/kubectl
                tag: v1.28.5
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
