apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.13
    helm:
      values: |
        controller:
          componentName: "jenkins-controller"
          serviceType: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
