apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"database-operator-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"database-operator-role"},"subjects":[{"kind":"ServiceAccount","name":"database-operator-sa","namespace":"platform-system"}]}
  creationTimestamp: "2026-08-24T19:26:37Z"
  labels:
    app.kubernetes.io/instance: root-app
  name: database-operator-binding
  resourceVersion: "43689"
  uid: c19e4a27-7649-438c-8c93-332909ce99bd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: database-operator-role
subjects:
- kind: ServiceAccount
  name: database-operator-sa
  namespace: platform-system
