apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: platform-system
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: AdminSuperSecretPassword123!
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-backend
  namespace: platform-system
  labels:
    app: postgres-backend
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: postgres-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-backend
  namespace: platform-system
spec:
  serviceName: postgres-backend
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backend
  template:
    metadata:
      labels:
        app: postgres-backend
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgresql
          envFrom:
            - secretRef:
                name: postgres-credentials
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
