apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-backend
  namespace: platform-system
spec:
  serviceName: postgres-backend
  replicas: 1
  selector:
    matchLabels:
      app: postgres-backend
  template:
    metadata:
      labels:
        app: postgres-backend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "postgresSecretPassword"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "platform"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: run-tmp
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: run-tmp
          emptyDir: {}
        - name: tmp
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
