apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2026-08-24T19:26:37Z"
  labels:
    app.kubernetes.io/instance: root-app
  name: database-operator-sa
  namespace: platform-system
  resourceVersion: "41130"
  uid: c20b3cc5-9bb5-4c4b-adb4-9b31ece941af
