apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: demo-app
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: postgres:16-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Starting Web Application Tier...";
            echo "Connecting to DB: $DB_NAME as user $DB_USER...";
            while true; do
              PGPASSWORD=$DB_PASS psql -h postgres-backend.platform-system.svc.cluster.local -U $DB_USER -d postgres -c "SELECT 1;" > /dev/null 2>&1;
              if [ $? -eq 0 ]; then
                echo "[Tue Aug 25 04:40:30 PM WAT 2026] Database Connection: SUCCESSFUL";
              else
                echo "[Tue Aug 25 04:40:30 PM WAT 2026] Database Connection: WAITING FOR DB ACK...";
              fi;
              sleep 10;
            done
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: webapp-db-claim-db-creds
              key: DATABASE_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: webapp-db-claim-db-creds
              key: DATABASE_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: webapp-db-claim-db-creds
              key: DATABASE_PASSWORD
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
  namespace: demo-app
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
