apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.chaos-mesh.org'
    chart: chaos-mesh
    targetRevision: 2.6.3
    helm:
      values: |
        chaosDaemon:
          runtime: containerd
          socketPath: /run/k3s/containerd/containerd.sock
        dashboard:
          create: true
          securityMode: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
