apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.24
    helm:
      values: |
        controller:
          componentName: "jenkins-controller"
          jenkinsOpts: "--prefix=/jenkins"
          jenkinsUrl: "http://172.18.20.115/jenkins/"
          serviceType: "ClusterIP"
          image:
            tag: "lts-jdk17"
          installPlugins:
            - "kubernetes"
            - "git"
            - "configuration-as-code"
          ingress:
            enabled: true
            ingressClassName: nginx
            paths:
              - "/jenkins"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
        persistence:
          enabled: true
          storageClass: "local-path"
          size: "10Gi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
