apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.8.24
    helm:
      values: |
        controller:
          componentName: "jenkins-controller"
          jenkinsOpts: "--prefix=/jenkins"
          jenkinsUrl: "http://172.18.20.115/jenkins/"
          javaOpts: "-Xmx1536m"
          serviceType: "ClusterIP"
          image:
            tag: "lts-jdk17"
          installPlugins: []
          healthProbes: true
          healthProbesCustomPath: "/jenkins/login"
          livenessProbe:
            httpGet:
              path: "/jenkins/login"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: "/jenkins/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
          ingress:
            enabled: true
            ingressClassName: nginx
            paths:
              - "/jenkins"
          resources:
            requests:
              cpu: "500m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
        persistence:
          enabled: true
          storageClass: "local-path"
          size: "10Gi"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
