apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 58.2.0
    helm:
      values: |
        prometheusOperator:
          crds:
            enabled: false
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false

        grafana:
          enabled: true
          adminPassword: "admin"
          "grafana.ini":
            server:
              domain: "172.18.20.115"
              root_url: "http://172.18.20.115/grafana/"
              serve_from_sub_path: true

          ingress:
            enabled: true
            ingressClassName: nginx
            path: /grafana
            pathType: Prefix
            hosts:
              - ""
        prometheus:
          prometheusSpec:
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Replace=true
